### ISSUE TITLE
E3D with GT2 pulleys

### ISSUE THREAD

**Issue by dangasaur** [nophead/Mendel90#64]
I see that the E3D branch does not have the GT2 pulley changeset.  Looking through the change set it seems like this is just a materials change and does not affect any printed parts (minus the removed T5 printed pulleys).  Is that correct?

**Comment by nophead** [comment]
No the printed parts will change as the belt is a different thickness and the belt clips have teeth in them.

**Comment by nophead** [comment]
master branch now supports E3D and uses GT2 pulleys.
