### ISSUE TITLE
Compile crashes at 'frame_base.dxf'

### ISSUE THREAD

**Issue by helifino** [nophead/Mendel90#68]
Copied a conf file, didn't make any changes. Compile fails.
Linux Mint 17
Python 2.7.6
OpenSCAD version 2014.01.29

[mysturdy_E3D_config.scad.txt](https://github.com/nophead/Mendel90/files/904577/mysturdy_E3D_config.scad.txt)

[openscad.log.txt](https://github.com/nophead/Mendel90/files/904573/openscad.log.txt)

**Comment by nophead** [comment]
README.md states OpenSCAD-2015.05 or later is required, so that is probably the reason it doesn't work.

**Comment by helifino** [comment]
Indeed, this is the bit I was missing.
